

# This file was *autogenerated* from the file setup_tables/setup_all.sage
from sage.all_cmdline import *   # import sage library

load_attach_path('/home/ben/dynabase')
import sys
sys.path.append("/home/ben/dynabase")

# set up tables
load("connect.py")
load("setup_tables/setup_all.py")


